pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // This step checks out your source code from your version control system
                checkout scm
            }
        }

        stage('Build and Run Tests') {
            steps {
                script {
                    // Assuming you have Maven installed on your Jenkins agent
                    sh 'mvn clean test'
                }
            }
        }
    }
}
